import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/config/auth";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"

  
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function  RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body  className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}>{children}</body>
      </html>
    </SessionProvider>
  );
}
